baseURL = 'https://www.timeforyou.bg/'
relativeURLs = "True"

languageCode = 'bg-BG'
defaultContentLanguage = "bg"
title = 'Офис масажи София - Time For You'

theme = 'scroll'

enableRobotsTXT = true

# In order to add version information in the page's footer set to true.
enableGitInfo = true

[taxonomies]
  tag = ""
  category = ""

[sitemap]
	changeFreq = 'weekly'
	disable = false
	filename = 'sitemap.xml'
	priority = 1.0

[params]
	relativeURLs = "True"

	favicon = "images/logo.jpg"

	description = 'Офис масажи в София от кинезитерапевт Стелияна Караиванова – мобилен масаж на работното място, 15 и 30 минутни сесии за екипи в офис сгради в София.'

	[params.meta]
		keywords = 'office massage, relax, Bulgaria, Sofia'

	copyright = "© Steliyana Karaivanova"

	# This theme will, by default, inject a design-by-line at the bottom of the page.
	# You can turn it off, but we would really appreciate if you don’t :-)
	hidedesignbyline = false

	[params.footer]
	# Show contact icons for email/phone (if specified) in the footer of the page
	showContactIcons = true

	# Show links indicated with footer_menu and footer_menu_title in the footer of the page
	showFooterLinks = true

	[[params.contacts]]
		label = "phone"
		value = "+35988 343 5371"
		url = "tel:+35988 343 5371"
		icon = "fa fa-phone"

	[[params.contacts]]
		label = "email"
		value = "steliyana.ka@gmail.com"
		url = "mailto:steliyana.ka@gmail.com"
		icon = "fa fa-envelope"

	[[params.contacts]]
		label = "address"
		value = "Промишлена зона Хладилника, бул. Филип Кутев 7"
		url = "https://maps.app.goo.gl/89AtBmfywV8ExR6x9"
		icon = "fa fa-address-card"

	[[params.contacts]]
		label = "facebook"
		value = "facebook"
		url = "https://www.facebook.com/profile.php?id=100064050252044"
		icon = "fa fa-book"

	[[params.contacts]]
		label = "linkedin"
		value = "linkedin"
		url = "https://www.linkedin.com/in/%D1%81%D1%82%D0%B5%D0%BB%D0%B8%D1%8F%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D0%B0%D0%B8%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0-b93b66340/"
		icon = "fa-brands fa-linkedin"
